// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REMOVED***Cu8AtVjmtcku_HRp29c6zc164qUysESfs',
    appId: 'REDACTED_APP_ID',
    messagingSenderId: 'REDACTED_MESSAGING_SENDER_ID',
    projectId: 'REDACTED_PROJECT_ID',
    authDomain: 'REDACTED_PROJECT_ID.firebaseapp.com',
    databaseURL: 'https://REDACTED_PROJECT_ID-default-rtdb.***REMOVED***',
    storageBucket: 'REDACTED_PROJECT_ID.***REMOVED***',
    measurementId: 'REDACTED_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***AI7m4QmdQM4-Hy8-URBTSqtCB0Dnitcmw',
    appId: '1:REDACTED_MESSAGING_SENDER_ID:android:c3d980af7c2385fa0771d7',
    messagingSenderId: 'REDACTED_MESSAGING_SENDER_ID',
    projectId: 'REDACTED_PROJECT_ID',
    databaseURL: 'https://REDACTED_PROJECT_ID-default-rtdb.***REMOVED***',
    storageBucket: 'REDACTED_PROJECT_ID.***REMOVED***',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REMOVED***A9wrM9qdEFcbsb8JvxZmKxYt81SMK_lfM',
    appId: '1:REDACTED_MESSAGING_SENDER_ID:ios:b5d8666013dc32ac0771d7',
    messagingSenderId: 'REDACTED_MESSAGING_SENDER_ID',
    projectId: 'REDACTED_PROJECT_ID',
    databaseURL: 'https://REDACTED_PROJECT_ID-default-rtdb.***REMOVED***',
    storageBucket: 'REDACTED_PROJECT_ID.***REMOVED***',
    iosBundleId: 'com.example.doAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '***REMOVED***Cu8AtVjmtcku_HRp29c6zc164qUysESfs',
    appId: '1:REDACTED_MESSAGING_SENDER_ID:web:fba7a1809989cabd0771d7',
    messagingSenderId: 'REDACTED_MESSAGING_SENDER_ID',
    projectId: 'REDACTED_PROJECT_ID',
    authDomain: 'REDACTED_PROJECT_ID.firebaseapp.com',
    databaseURL: 'https://REDACTED_PROJECT_ID-default-rtdb.***REMOVED***',
    storageBucket: 'REDACTED_PROJECT_ID.***REMOVED***',
    measurementId: 'G-R6MZQYTGGZ',
  );
}
